sudo: require
services:
    - docker
    
before_install:
    - docker build -t ncachulo/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true ncachulo/docker-react npm run test -- --coverage